# Generated by Django 4.2.7 on 2023-12-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='name',
            field=models.TextField(max_length=1000),
        ),
    ]
