# Generated by Django 4.1.7 on 2023-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_produit_description_alter_produit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
