# Generated by Django 4.2.7 on 2023-12-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_actif_userprofile_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
